//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZwitsTestEngine
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class AdminTable
    {
        public int AdminId { get; set; }
        public string AdminPassword { get; set; }
    }
}
