//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZwitsTestEngine
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class StudentExamTable
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public string StudentSet { get; set; }
        public string StudentSubject1 { get; set; }
        public string StudentSubject2 { get; set; }
        public string StudentSubject3 { get; set; }
        public Nullable<int> StudentScore1 { get; set; }
        public Nullable<int> StudentScore2 { get; set; }
        public Nullable<int> StudentScore3 { get; set; }
        public Nullable<int> StudentTotalScore { get; set; }
    }
}
