//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZwitsTestEngine
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Table
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string ExamID { get; set; }
        public string ExamType { get; set; }
        public byte[] Passport { get; set; }
    }
}
